# Hexo Configuration

# Site 网站相关配置
title: '欢迎来到爱谦 717 的博客'
subtitle: '永远相信美好的事情即将发生'
description: '永远相信美好的事情即将发生'
keywords: 个人博客
author: bcZhang
language: zh-CN
timezone: 'Asia/Shanghai'

# URL 网站链接配置
url: https://bczhang717.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true
  trailing_html: true

# Directory 目录配置
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing 文章相关设置
new_post_name: :title.md # 新文章的文件名称
default_layout: post # 预设布局
titlecase: false # 是否把标题转换为 title case
external_link:
  enable: true # 是否在新标签中打开链接
  field: site # 对整个网站(site)生效或仅对文章(post)生效
  exclude: '' # 需要排除的域名
filename_case: 0 # 0-按照自己的命名规则; 1-文件名全部转换为小写; 2-文件名全部转换为大写;
render_drafts: false # 是否显示草稿
post_asset_folder: false # 是否启用资源文件夹
relative_link: false # 是否把链接改为与根目录的相对位址
future: true # 是否显示未来的文章
syntax_highlighter: highlight.js # 代码块的设置
highlight: # 代码块的设置, 后续再说
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs: # 代码块的设置, 后续再说
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting 首页设置
index_generator:
  path: '' # 博客索引页面的根路径
  per_page: 5 # 每页显示帖子数
  order_by: -date # 帖子排列顺序, 目前是按日期倒序排列(从新到旧)

# Category & Tag setting 分类和标签设置
default_category: uncategorized # 默认分类
category_map: # 分类别名
tag_map: # 标签别名

# Metadata elements
meta_generator: true

# Date / Time format 时间格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination 分页设置
per_page: 10 # 每页显示帖子数
pagination_dir: page # 分页路径

# Include / Exclude file(s) # 包括或不包括目录和文件
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions 扩展
theme: butterfly # 主题名称

# Deployment 部署
deploy:
  type: 'git'
  repository: 'git@github.com:bcZhang717/bcZhang717.github.io.git'
  branch: 'main'
search:
  path: search.xml
  field: post
  format: html
  limit: 10000